server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: tailr-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/tailr}
    username: ${SPRING_DATASOURCE_USERNAME:tailr}
    password: ${SPRING_DATASOURCE_PASSWORD:tailr}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${SUPABASE_JWKS_URL:http://localhost:9999/mock-jwks}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: when_authorized
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    org.springframework.security: INFO
    org.hibernate.SQL: INFO

app:
  supabase:
    project-url: ${SUPABASE_PROJECT_URL:}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}


